/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <VectorKit/VKIconAtlas.h>

__attribute__((visibility("hidden")))
@interface _VKLocalIconAtlas : VKIconAtlas
{
}

- (struct CGImage *)_createImageForName:(id)arg1 contentScale:(float)arg2;

@end

