/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMapTable, VGLResourceFactory;

__attribute__((visibility("hidden")))
@interface VGLProgramFactory : NSObject
{
    VGLResourceFactory *_factory;
    NSMapTable *_programCache;
}

@property(nonatomic) VGLResourceFactory *factory; // @synthesize factory=_factory;
- (id)programWithClass:(Class)arg1;
- (id)initWithResourceFactory:(id)arg1;

@end

