/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <VectorKit/VKScene.h>

#import "NSCopying.h"

__attribute__((visibility("hidden")))
@interface VKRasterOverlayScene : VKScene <NSCopying>
{
    unsigned int _overlayLevel;
}

@property(nonatomic) unsigned int overlayLevel; // @synthesize overlayLevel=_overlayLevel;

@end

