/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class VKStylesheet;

@protocol VKStylesheetObserver <NSObject>
+ (BOOL)reloadOnStylesheetChange;
@property(readonly, nonatomic) VKStylesheet *stylesheet;

@optional
- (void)stylesheetDoneChanging;
- (void)stylesheetDidChange;
- (void)stylesheetWillChange;
- (void)prepareForStylesheetTransitionToMapDisplayStyle:(int)arg1 withReadinessBlock:(id)arg2;
@end

