/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <PassKitCore/PKPass.h>

#import "NSSecureCoding.h"

@class NSString;

@interface PKBundledPass : PKPass <NSSecureCoding>
{
    NSString *_imageBase;
}

+ (BOOL)supportsSecureCoding;
+ (id)passWithBundledStyle:(int)arg1;
@property(retain, nonatomic) NSString *imageBase; // @synthesize imageBase=_imageBase;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)fetchImageSet:(int)arg1 withCompletion:(id)arg2;
- (BOOL)contentIsLoaded;
- (void)dealloc;
- (id)initWithBundledStyle:(int)arg1;

@end

