/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface CAAnimationDelegateBlockHelper : NSObject
{
    id _animationDidStartBlock;
    id _animationDidStopBlock;
}

@property(copy, nonatomic) id animationDidStopBlock; // @synthesize animationDidStopBlock=_animationDidStopBlock;
@property(copy, nonatomic) id animationDidStartBlock; // @synthesize animationDidStartBlock=_animationDidStartBlock;
- (void)animationDidStop:(id)arg1 finished:(BOOL)arg2;
- (void)animationDidStart:(id)arg1;
- (void)dealloc;

@end

