/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UICollectionReusableView.h"

@class NSString, UILabel;

__attribute__((visibility("hidden")))
@interface SFCollectionViewFooter : UICollectionReusableView
{
    UILabel *_headerLabel;
    UILabel *_textLabel;
}

+ (struct CGSize)sizeThatFits;
- (void).cxx_destruct;
@property(readonly, nonatomic) int numberOfLines;
@property(readonly, nonatomic) NSString *footerText;
- (void)setTextColor:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

