/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UICollectionViewCell.h"

@class SFAirDropAnimatedIconView;

__attribute__((visibility("hidden")))
@interface SFPlaceholderCollectionViewCell : UICollectionViewCell
{
    SFAirDropAnimatedIconView *_iconView;
}

- (void).cxx_destruct;
@property(nonatomic, getter=isAnimating) BOOL animate;
- (id)initWithFrame:(struct CGRect)arg1;

@end

