/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIView.h"

#import "SBUIBannerView.h"

@interface SBUIRoundedBannerView : UIView <SBUIBannerView>
{
    UIView *_backgroundShadowView;
    UIView *_contentContainerView;
    UIView *_contentView;
    UIView *_underlayView;
}

- (id)bannerContext;
- (void)drawStretchableBackground:(struct CGContext *)arg1;
- (id)contentView;
- (id)bannerItem;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

