/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@interface SBUIPluginAppearanceContext : NSObject
{
    unsigned int _uiEnvironment;
}

@property(nonatomic) unsigned int uiEnvironment; // @synthesize uiEnvironment=_uiEnvironment;

@end

