/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@protocol UserFSItem <NSObject>
@property(readonly, nonatomic) struct timespec modifiedDate;
@property(readonly, nonatomic) struct timespec createdDate;
@property(readonly, nonatomic) unsigned long long length;
@property(readonly, nonatomic, getter=isLocked) BOOL locked;
@property(readonly, nonatomic) BOOL isDirectory;
@property(readonly, nonatomic) NSString *name;
@property(readonly, nonatomic) id <UserFSVolume> volume;
@end

