/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UserFSItem.h"

@protocol UserFSFolder <UserFSItem>
- (int)readChildrenIntoArray:(id)arg1 withState:(id *)arg2;
- (BOOL)deleteChildNamed:(id)arg1;
- (id)childNamed:(id)arg1;
@end

