/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "PSSettingsBoolDetail.h"

@interface PSCellularDataSettingsDetail : NSObject <PSSettingsBoolDetail>
{
}

+ (BOOL)deviceSupportsCellularData;
+ (BOOL)isEnabled;
+ (void)setEnabled:(BOOL)arg1;
+ (id)iconImage;
+ (id)preferencesURL;

@end

