/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <WebContentAnalysis/WFTagFlyweight.h>

__attribute__((visibility("hidden")))
@interface WFDocumentStructureTag : WFTagFlyweight
{
}

+ (id)tagForNumberOfPixels:(int)arg1;
+ (id)tagForNumberOfImages:(int)arg1;
- (id)tagWithWebpage:(id)arg1;

@end

