/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <WebContentAnalysis/WFTagFlyweight.h>

__attribute__((visibility("hidden")))
@interface WFUSC2257Tag : WFTagFlyweight
{
}

+ (id)eighteenTag;
+ (id)unitedStatesCodeTag;
+ (id)twoTwoFiveSevenTag;
- (id)tagWithWebpage:(id)arg1;

@end

