/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <AirPortAssistant/StepByStepUIViewController_DevicePicker.h>

#import "StepByStepUIDevicePicker.h"

@interface StepByStepUIViewController_ReplaceNetworkChoice : StepByStepUIViewController_DevicePicker <StepByStepUIDevicePicker>
{
}

- (id)devicePickerLabel;
- (id)deviceTableLabel;
- (void)setupDevices;
- (void)updateNavigationButtons;
- (void)prepareParams;
- (void)setupHeaderAndFooter;

@end

