/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol CUIThemeImageSource <NSObject>
- (BOOL)hasValueSlices;
- (struct CGSize)imageSize;
- (id)imageForState:(int)arg1 withValue:(int)arg2;
- (id)imageForState:(int)arg1;
@end

