/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol MFMailPopoverManagerDelegate <NSObject>

@optional
- (BOOL)popoverControllerSupportsRotation:(id)arg1;
- (void)popoverControllerDidDismissPopover:(id)arg1 isUserAction:(BOOL)arg2;
- (BOOL)popoverControllerShouldDismissPopover:(id)arg1;
@end

