/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol MFMessageBodyStringAccumulator <NSObject>
- (void)appendCustomEntityWithTag:(unsigned int)arg1 stringRepresentation:(id)arg2;
- (id)accumulatedString;
- (void)appendInnerTextWithConsumableNode:(id)arg1;
- (void)appendCharacters:(const unsigned short *)arg1 length:(unsigned int)arg2;
- (void)appendRange:(struct _NSRange)arg1 ofString:(id)arg2;
- (void)appendString:(id)arg1;
- (BOOL)isFull;
@end

