/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class NSNumber, NSString;

@protocol TIUserDictionaryEntry <NSObject>
@property(retain, nonatomic) NSNumber *timestamp;
@property(copy, nonatomic) NSString *shortcut;
@property(copy, nonatomic) NSString *phrase;
@end

