/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol AirPlayDiagnosticsFullscreenControllerDelegate <NSObject>

@optional
- (id)includeAttachmentDataInAirPlayDiagnosticsFullscreenController:(id)arg1;
- (id)includeApplicationIssuesInAirPlayDiagnosticsFullscreenController:(id)arg1;
- (void)airPlayDiagnosticsFullscreenController:(id)arg1 didComplete:(BOOL)arg2;
@end

