/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol MPAVPlaylistFeeder <NSObject>
@property(readonly, nonatomic) unsigned int nonRepeatingItemCount;
@property(readonly, nonatomic) unsigned int itemCount;
@property(readonly, nonatomic) unsigned int initialPlaybackQueueDepth;
- (BOOL)shouldReloadForChangeFromNetworkType:(int)arg1 toNetworkType:(int)arg2;
- (id)itemForIndex:(unsigned int)arg1;
- (BOOL)hasItemForIndex:(unsigned int)arg1;
- (void)assumeOwnershipOfItems:(id)arg1;
@end

