/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <MediaPlayer/MPFullScreenVideoViewController.h>

@interface MPMoviePlayerVideoViewController : MPFullScreenVideoViewController
{
    BOOL _hideNavigationBar;
}

@property(nonatomic) BOOL hideNavigationBar; // @synthesize hideNavigationBar=_hideNavigationBar;
- (void)showOverlayAnimated:(BOOL)arg1;
- (void)backgroundViewDidUpdate;

@end

