/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@interface CalendarMessageUIProxy : NSObject
{
}

+ (Class)MFMessageComposeViewControllerClass;
+ (Class)MFMailComposeViewControllerClass;
+ (Class)MFContactsSearchResultsModelClass;
+ (Class)MFContactsSearchManagerClass;
+ (Class)SearchShadowViewClass;
+ (Class)RecipientTableViewCellClass;
+ (Class)ComposeRecipientViewClass;
+ (Class)MailComposeRecipientClass;
+ (Class)CalendarComposeRecipientClass;

@end

