/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <EventKitUI/EKEventDetailItem.h>

#import "EKEventDetailTitleCellDelegate.h"

@class EKEventInfoHeaderView, NSObject<EKEventTitleDetailItemDelegate>, UIColor, UITableViewCell;

__attribute__((visibility("hidden")))
@interface EKEventTitleDetailItem : EKEventDetailItem <EKEventDetailTitleCellDelegate>
{
    UITableViewCell *_cell;
    EKEventInfoHeaderView *_header;
    UIColor *_color;
    BOOL _showDot;
    NSObject<EKEventTitleDetailItemDelegate> *_editDelegate;
}

@property(nonatomic) __weak NSObject<EKEventTitleDetailItemDelegate> *editDelegate; // @synthesize editDelegate=_editDelegate;
- (void).cxx_destruct;
- (BOOL)shouldShowEditButtonInline;
- (void)editButtonPressed;
- (id)cellForSubitemAtIndex:(unsigned int)arg1;
- (float)defaultCellHeightForSubitemAtIndex:(unsigned int)arg1 forWidth:(float)arg2;
- (BOOL)configureWithCalendar:(id)arg1 preview:(BOOL)arg2;
- (void)reset;

@end

