/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <EventKitUI/EKEventDetailTwoValueCell.h>

__attribute__((visibility("hidden")))
@interface EKEventDetailAlarmCell : EKEventDetailTwoValueCell
{
}

- (BOOL)update;
- (void)setAlarms:(id)arg1;
- (BOOL)isEditable;
- (id)initWithEvent:(id)arg1 editable:(BOOL)arg2 platformStyle:(int)arg3;

@end

