/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <EventKitUI/EKEventDetailCell.h>

__attribute__((visibility("hidden")))
@interface EKEventDetailPreviewCell : EKEventDetailCell
{
    BOOL _alwaysVisible;
}

@property(nonatomic) BOOL alwaysVisible; // @synthesize alwaysVisible=_alwaysVisible;
- (BOOL)update;
- (id)initWithEvent:(id)arg1 editable:(BOOL)arg2;

@end

