/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <MusicLibrary/ML3DatabaseResult.h>

__attribute__((visibility("hidden")))
@interface ML3ContainerDatabaseResult : ML3DatabaseResult
{
    unsigned int _limitIndex;
    long long _limitValue;
}

- (void)enumerateRowsWithBlock:(id)arg1;
- (id)initWithStatement:(id)arg1 limitProperty:(id)arg2 limitValue:(long long)arg3;

@end

