/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol RCCurrentRecordingViewControllerDelegate <NSObject>
- (void)currentRecordingViewController:(id)arg1 didDeterminteAvailability:(BOOL)arg2;
- (void)currentRecordingViewControllerRecordingDidEnd:(id)arg1;
@end

