/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface WebCoreTextTrackRepresentationIOSHelper : NSObject
{
    struct TextTrackRepresentationIOS *_parent;
}

- (id)actionForLayer:(id)arg1 forKey:(id)arg2;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)drawLayer:(id)arg1 inContext:(struct CGContext *)arg2;
@property struct TextTrackRepresentationIOS *parent;
- (void)dealloc;
- (id)initWithParent:(struct TextTrackRepresentationIOS *)arg1;

@end

