/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIView.h"

@class NSAttributedString, NSDictionary, UIColor;

__attribute__((visibility("hidden")))
@interface MKCompassView : UIView
{
    float _yaw;
    float _degrees;
    float _scale;
    UIColor *_discColor;
    UIColor *_ticColor;
    UIColor *_arrowColor;
    NSAttributedString *_nString;
    struct CGPoint _nStringDrawPoint;
    NSDictionary *_degreeFontAttributes;
}

- (void)drawRect:(struct CGRect)arg1;
@property(nonatomic) float yaw; // @dynamic yaw;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

