/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface MKMapAttributionImage : NSObject
{
    NSString *_hidpiImageName;
    NSString *_lodpiImageName;
}

- (id)imageNameForScale:(float)arg1;
- (void)dealloc;
- (id)initWithAttributions:(id)arg1 type:(int)arg2;

@end

