/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

@protocol MKOverlayContainerViewDelegate
- (id)vk_mapLayer;
- (CDStruct_90e2a262)visibleMapRect;
- (id)createDrawableForOverlay:(id)arg1;
- (void)overlayContainerAddedDrawables:(id)arg1;
@end

