/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <MapKit/MKPolyline.h>

@class MKRoutePolyline;

__attribute__((visibility("hidden")))
@interface MKRouteStepPolyline : MKPolyline
{
    MKRoutePolyline *_fullRoute;
}

- (void)dealloc;
- (id)_initWithRoute:(id)arg1 range:(struct _NSRange)arg2;

@end

