/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"
#import "UITableViewDelegate.h"

@protocol IUCZAlbumTableViewControllerDelegate <UITableViewDelegate, NSObject>

@optional
- (void)albumTableViewDidTapAlbumArtwork:(id)arg1;
@end

