/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray, TSUNoCopyDictionary;

__attribute__((visibility("hidden")))
@interface OADGraphicFeatureCache : NSObject
{
    NSMutableArray *mFeatureUsageArray;
    TSUNoCopyDictionary *mFeatureMap;
}

- (id)featuresSortedByUsageCount;
- (id)countedFeatureAtIndex:(unsigned int)arg1;
- (unsigned int)cacheFeature:(id)arg1;
- (void)dealloc;
- (id)init;

@end

