/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class NSDictionary;

__attribute__((visibility("hidden")))
@interface OADImageRecolorInfo : NSObject
{
    NSDictionary *mColors;
    NSDictionary *mFills;
}

- (BOOL)isEqual:(id)arg1;
- (unsigned int)hash;
- (id)fills;
- (id)colors;
- (void)dealloc;
- (id)initWithColors:(id)arg1 fills:(id)arg2;

@end

