/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <OfficeImport/PDTimeNode.h>

@class PDAnimationTarget;

__attribute__((visibility("hidden")))
@interface PDAnimateBehavior : PDTimeNode
{
    PDAnimationTarget *mTgtElement;
}

- (void)setTarget:(id)arg1;
- (id)target;
- (void)dealloc;
- (id)init;

@end

