/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <OfficeImport/PDMediaNode.h>

__attribute__((visibility("hidden")))
@interface PDVideoNode : PDMediaNode
{
    BOOL mIsFullScreen;
}

- (void)setIsFullScreen:(BOOL)arg1;
- (BOOL)isFullScreen;

@end

