/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol PTSImageLoaderDelegate <NSObject>
- (void)imageLoaderDidFinishLoadingImages:(id)arg1;
- (void)imageLoader:(id)arg1 didLoadImage:(id)arg2 forFilename:(id)arg3;
@end

