/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol PLNavigableAssetContainerListViewController <NSObject>
- (void)navigateToRevealAssetContainer:(id)arg1 initiallyHidden:(BOOL)arg2 animated:(BOOL)arg3;
- (void)navigateToAssetContainer:(id)arg1 animated:(BOOL)arg2 completion:(id)arg3;
@end

