/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol PUPhotoStreamComposeServiceDelegate <NSObject>
- (void)photoStreamComposeServiceDidCancel:(id)arg1;
- (void)photoStreamComposeServiceDidPost:(id)arg1;
@end

