/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol PUPhotoStreamsAlbumsTableViewControllerDelegate <NSObject>
- (void)controllerWillCreateNewAlbum:(id)arg1;
- (void)controller:(id)arg1 didSelectAlbum:(struct NSObject *)arg2;
@end

