/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol PUStackedAlbumControllerTransition <NSObject>
- (void)setAlbumListTransitionLayout:(id)arg1 animated:(BOOL)arg2;
- (void)setAlbumListTransitionContext:(id)arg1;
- (id)gridLayout;
- (id)collectionView;
- (BOOL)isEmpty;
@end

