/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@interface LocationDefaults : NSObject
{
}

+ (void)restartLocationDaemon;
+ (id)getLocationDefaultsValueForKey:(id)arg1;
+ (void)setLocationDefaultsValue:(id)arg1 forKey:(id)arg2;

@end

