/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <UIFoundation/UIFont.h>

__attribute__((visibility("hidden")))
@interface UICTFont : UIFont
{
}

- (void)finalize;
- (unsigned int)retainCount;
- (BOOL)retainWeakReference;
- (BOOL)allowsWeakReference;
- (oneway void)release;
- (id)retain;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (unsigned long)_cfTypeID;

@end

