/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class NSXPCConnection, Protocol;

__attribute__((visibility("hidden")))
@interface ACXPCProxyHelper : NSObject
{
    NSXPCConnection *_connection;
    Protocol *_protocol;
}

- (void).cxx_destruct;
- (void)_callReplyHandlerForInvocation:(id)arg1 withError:(id)arg2;
- (void)forwardInvocation:(id)arg1;
- (id)methodSignatureForSelector:(SEL)arg1;
- (id)initWithXPCConnection:(id)arg1 protocol:(id)arg2;

@end

