/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <ScreenReaderCore/SCRCPhotoEvaluatorResult.h>

__attribute__((visibility("hidden")))
@interface SCRCPhotoEvaluatorResultBlur : SCRCPhotoEvaluatorResult
{
    float _blurLevel;
}

@property(readonly, nonatomic) float blurLevel; // @synthesize blurLevel=_blurLevel;
- (id)humanReadableResult;
- (id)initWithBlurLevel:(float)arg1;

@end

