/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <Social/SLSheetPreviewImageView.h>

@class CALayer;

__attribute__((visibility("hidden")))
@interface SLSheetBevelledImageView : SLSheetPreviewImageView
{
    CALayer *_frameLayer;
}

- (void).cxx_destruct;
- (struct CGSize)intrinsicContentSize;
- (struct UIEdgeInsets)alignmentRectInsets;
- (id)init;

@end

