/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <Social/SLSheetPreviewImageView.h>

@class UIImage;

__attribute__((visibility("hidden")))
@interface SLSheetPreComposedAppIconImageView : SLSheetPreviewImageView
{
    UIImage *_shadowImage;
}

- (void).cxx_destruct;
- (struct CGSize)intrinsicContentSize;
- (struct UIEdgeInsets)alignmentRectInsets;
- (void)setImage:(id)arg1;
- (id)init;

@end

