/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <Social/SLService.h>

__attribute__((visibility("hidden")))
@interface SLYoukuService : SLService
{
}

- (BOOL)isFirstClassService;
- (int)authenticationStyle;
- (id)accountTypeIdentifier;
- (id)serviceType;

@end

