/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface WECoreSig1Signer : NSObject
{
}

+ (id)signatureForBaseString:(id)arg1 withKey:(id)arg2;
+ (id)_hmacSha1SignatureForBaseString:(id)arg1 withKey:(id)arg2;
+ (id)_asciiStringToHexString:(id)arg1;

@end

