/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <CoreImage/CIFilter.h>

#import "_CIFilterProperties.h"

@class CIImage, CIVector;

__attribute__((visibility("hidden")))
@interface CICrop : CIFilter <_CIFilterProperties>
{
    CIImage *inputImage;
    CIVector *inputRectangle;
}

+ (id)customAttributes;
@property(retain, nonatomic) CIVector *inputRectangle; // @synthesize inputRectangle;
@property(retain, nonatomic) CIImage *inputImage; // @synthesize inputImage;
- (id)_initFromProperties:(id)arg1;
- (id)_outputProperties;
- (id)outputImage;
- (void)setDefaults;

@end

