/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <CoreImage/CICodeGenerator.h>

__attribute__((visibility("hidden")))
@interface CIQRCodeGenerator : CICodeGenerator
{
}

+ (id)customAttributes;
- (struct CGImage *)outputCGImage;
- (void)setDefaults;

@end

