/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <CommunicationsSetupUI/CNFRegModernAppearanceController.h>

@interface CNFRegModernTransparentAppearanceController : CNFRegModernAppearanceController
{
}

- (id)navigationBarTintColor;
- (int)navigationBarActivityIndicatorStyle;
- (int)modalPresentationStyle;
- (id)splashSignInFieldsBackgroundColor;
- (id)splashSignInFieldsBorderColor;
- (id)splashEntryPlaceholderTextColor;
- (id)splashEntryFieldTextColor;
- (BOOL)splashScreenShowsIcon;
- (id)tableCellCheckmarkImageDisabled;
- (id)tableBackgroundColor;

@end

