/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

__attribute__((visibility("hidden")))
@interface __NSMessageBuilder
{
    Class isa;
    id _target;
    id *_addr;
}

+ (void)initialize;
- (id)methodSignatureForSelector:(SEL)arg1;
- (void)forwardInvocation:(id)arg1;
- (void)finalize;

@end

