/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <CoreFoundation/__NSCFString.h>

__attribute__((visibility("hidden")))
@interface __NSCFConstantString : __NSCFString
{
}

- (id)autorelease;
- (unsigned int)retainCount;
- (oneway void)release;
- (id)retain;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (BOOL)isKindOfClass:(Class)arg1;

@end

