/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <StoreKitUI/SKUILoadResourceOperation.h>

@class SKUIItemResourceRequest;

@interface SKUILoadItemResourceOperation : SKUILoadResourceOperation
{
}

- (void)main;
- (id)initWithResourceRequest:(id)arg1;

// Remaining properties
@property(readonly) SKUIItemResourceRequest *resourceRequest; // @dynamic resourceRequest;

@end

