/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol SKUISlideshowItemViewControllerDelegate <NSObject>
- (void)slideshowItemViewControllerDidDismissWithPinchGesture:(id)arg1 ratio:(float)arg2;
- (void)slideshowItemViewControllerDidBeginPinchGesture:(id)arg1;
@end

