/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol SKUISearchRelatedViewDelegate <NSObject>
- (void)searchRelatedViewDidSelectBackButton:(id)arg1;
- (void)searchRelatedView:(id)arg1 didSelectRelatedQueryAtIndex:(int)arg2;
@end

