/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol SKUIFlowcaseViewDelegate <NSObject>

@optional
- (void)flowcaseViewDidEndDecelerating:(id)arg1;
- (void)flowcaseView:(id)arg1 didSelectViewAtIndex:(int)arg2;
@end

