/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol SKUISlideshowViewControllerDelegate <NSObject>
- (id)slideshowViewController:(id)arg1 poppedImageViewAtIndex:(int)arg2;
- (void)slideshowViewController:(id)arg1 scrollToImageAtIndex:(int)arg2;
@end

