/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol SKUISlideshowViewControllerDataSource <NSObject>
- (int)numberOfItemsInSlideshowViewController:(id)arg1;

@optional
- (id)slideshowViewController:(id)arg1 imageURLAtIndex:(int)arg2 size:(struct CGSize *)arg3;
- (id)slideshowViewController:(id)arg1 imageAtIndex:(int)arg2;
@end

