/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <EventKit/EKCalendarDate.h>

__attribute__((visibility("hidden")))
@interface EKMutableCalendarDate : EKCalendarDate
{
}

- (void)addGregorianUnits:(CDStruct_6e43267c)arg1;
- (void)addDays:(int)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

