/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIView.h"

@interface UIView (iAd_Extras)
- (struct CGRect)_iAd_screenFrame;
- (BOOL)_iAd_isVisibleFast;
- (BOOL)_iAd_isVisible;
@end

