/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSSecureCoding.h"

@class NSData;

@interface PBCodable : NSObject <NSSecureCoding>
{
}

+ (BOOL)supportsSecureCoding;
- (id)dictionaryRepresentation;
- (void)writeTo:(id)arg1;
- (BOOL)readFrom:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
@property(readonly, nonatomic) NSData *data;
- (id)initWithData:(id)arg1;
- (id)init;

@end

