/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <SAObjects/AceObject.h>

#import "SAAceSerializable.h"

@class NSString, NSURL;

@interface SASPronunciationContext : AceObject <SAAceSerializable>
{
}

+ (id)pronunciationContextWithDictionary:(id)arg1 context:(id)arg2;
+ (id)pronunciationContext;
@property(copy, nonatomic) NSString *orthography;
@property(copy, nonatomic) NSString *domainObjectPropertyIdentifier;
@property(copy, nonatomic) NSURL *domainObjectIdentifier;
- (id)encodedClassName;
- (id)groupIdentifier;

@end

