/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <UIKit/_UIBackdropViewSettings.h>

__attribute__((visibility("hidden")))
@interface _UIBackdropViewSettingsVignette : _UIBackdropViewSettings
{
    int _vignetteSeeSaw;
}

@property(nonatomic) int vignetteSeeSaw; // @synthesize vignetteSeeSaw=_vignetteSeeSaw;
- (void)computeOutputSettingsUsingModel:(id)arg1;
- (void)setDefaultValues;

@end

