/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <UIKit/UIKBRenderFactory10Key.h>

__attribute__((visibility("hidden")))
@interface UIKBRenderFactory10Key_Portrait : UIKBRenderFactory10Key
{
}

- (void)setupLayoutSegments;
- (float)controlColumnWidthFactor;
- (id)muttitapReverseKeyImageName;
- (id)multitapCompleteKeyImageName;

@end

