/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"
#import "UITableViewDataSource.h"

@protocol ABContactViewDataSource <NSObject, UITableViewDataSource>

@optional
- (id)contactView:(id)arg1 cellForItemAtIndex:(int)arg2 inGroup:(id)arg3;
- (int)contactView:(id)arg1 numberOfItemsInGroup:(id)arg2;
@end

