/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol ABFMFActionButtonsDelegate <NSObject>
- (void)showFMFCallButton:(BOOL)arg1 withAction:(id)arg2;
- (void)showFMFFacetimeButton:(BOOL)arg1 withAction:(id)arg2;
- (void)showFMFMessageButton:(BOOL)arg1 withAction:(id)arg2;
@end

