/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIColor.h"

@interface UIColor (ABUIDefaultColors)
+ (id)cardCellSeparatorColor;
+ (id)cardCellReadonlyBackgroundColor;
+ (id)cardCellBackgroundColor;
+ (id)cardValueReadonlyTextColor;
+ (id)cardValueTextColor;
+ (id)cardLabelReadonlyTextColor;
+ (id)ab_colorWithR:(float)arg1 G:(float)arg2 B:(float)arg3 A:(float)arg4;
@end

